customhost = "database-1.cqhfmn45wiis.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "johnston-employee"
custombucket = "johnston-employee"
customregion = "us-east-1"
